import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "none"

opacity = 0.6
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"

size = 12


